### ISSUE TITLE
No Notification window pop up?

### ISSUE THREAD

**Issue by adidasbrandon** [Kadauchi/prolific-assistant#24]
Hi there been using the assistant for months now without issue's but in the last day or two im noticing the prolific assistant is making the sound notification when there's a new study but no pop up window on windows or action center... and i've got notifications enabled on the extension and in windows for chrome. Is this a known issue or bug? I hope it gets fixed soon! Thanks for all you do!

**Comment by transiient** [comment]
Partner has the same issue on Chrome. Uninstall then reinstall, @adidasbrandon, and it should fix itself with any luck. For the record I'm on Firefox and I've had no issue.

**Comment by adidasbrandon** [comment]
> Partner has the same issue on Chrome. Uninstall then reinstall, @adidasbrandon, and it should fix itself with any luck. For the record I'm on Firefox and I've had no issue.

Hey there @sam-cross thanks for the post i tried removing the extension and re downloading from the chrome store but its still not showing notifications on chrome... :/
